spring.application.name=hacksmdc

#PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-blue-flower-a1wc4kna-pooler.ap-southeast-1.aws.neon.tech:5432/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_uSNZW1XoY5Ga

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


#SMTP
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sandeephamba@gmail.com
spring.mail.password=ueyt fivn beuc pqji

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true